### ISSUE TITLE
webhook is not receiving the payload

### ISSUE THREAD

**Issue by aliry** [jeroentvb/IFTTT-webhooks-channel#12]
The issue is IFTTT seems to changed their URL for when providing json payload and it is not same as when calling the webhook with no payload.
The new URL looks like this:
https://maker.ifttt.com/trigger/{event}/json/with/key/xxxxxxxxxxxxxx

while the url for requests with no payload looks like this: (this the one is currently used in this package)
https://maker.ifttt.com/trigger/{event}/with/key/xxxxxxxxxxxxxx

**Comment by aliry** [comment]
I've created a PR to fix it
#13

**Comment by jeroentvb** [comment]
I've just had a look at the documentation. The 'old' url should work with and without a payload. Is that why you closed this issue?

**Comment by juan-cazalvilla** [comment]
Two years late but ... If you really need to send the payload, then the new URL must be used.

**Comment by jeroentvb** [comment]
I tested yesterday with and without payload, and ifttt registered my webhook call both with and without a payload. So the 'new' url (with `/json`) isn't mandatory.
